{% set name = "spotpy" %}
{% set version = "1.5.7" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7161ce5c0a095983d0ace48fa71faaa3436f37bc93c6f5225da3c9d4081c1ac4

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv "

requirements:
  host:
    - pip
    - python
  run:
    - python
    - numpy
    - scipy
    - pandas
    - matplotlib
    - mpi4py
    - pathos
    - pytables
    - numba

test:
  imports:
    - spotpy
    - spotpy.algorithms
    - spotpy.database
    - spotpy.examples
    - spotpy.examples.cmf_data
    - spotpy.examples.hymod_exe
    - spotpy.examples.hymod_python
    - spotpy.gui
    - spotpy.hydrology
    - spotpy.parallel

about:
  home: http://fb09-pasig.umwelt.uni-giessen.de/spotpy/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Statistical Parameter Optimization Tool
  description: |
    SPOTPY is a Python framework that enables the use of Computational optimization techniques for calibration, 
    uncertainty and sensitivity analysis techniques of almost every (environmental-) model. The package is published 
    in the open source journal PLoS One:

    Houska, T., Kraft, P., Chamorro-Chavez, A. and Breuer, L.: SPOTting Model Parameters Using a Ready-Made Python 
    Package, PLoS ONE, 10(12), e0145180, doi:10.1371/journal.pone.0145180, 2015.
  doc_url: http://fb09-pasig.umwelt.uni-giessen.de/spotpy/
  dev_url: https://github.com/thouska/spotpy

extra:
  recipe-maintainers:
    - volpatto
