{% set name = "spotpy" %}
{% set version = "1.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5bad39a4d7605167a7874bc8b8eca72708b9ee0e7a3fb7088204333dbdf77350

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps -vv '

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - numpy
    - scipy
    - pandas
    - matplotlib-base
    - mpi4py
    - pathos
    - click
    - numba

test:
  imports:
    - spotpy
    - spotpy.algorithms
    - spotpy.database
    - spotpy.examples
    - spotpy.examples.cmf_data
    - spotpy.examples.hymod_exe
    - spotpy.examples.hymod_python
    - spotpy.gui
    - spotpy.hydrology
    - spotpy.parallel

about:
  home: https://spotpy.readthedocs.io/en/latest/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Statistical Parameter Optimization Tool
  description: |
    SPOTPY is a Python framework that enables the use of Computational optimization techniques for calibration, 
    uncertainty and sensitivity analysis techniques of almost every (environmental-) model. The package is published 
    in the open source journal PLoS One:

    Houska, T., Kraft, P., Chamorro-Chavez, A. and Breuer, L.: SPOTting Model Parameters Using a Ready-Made Python 
    Package, PLoS ONE, 10(12), e0145180, doi:10.1371/journal.pone.0145180, 2015.
  doc_url: https://spotpy.readthedocs.io/en/latest/
  dev_url: https://github.com/thouska/spotpy

extra:
  recipe-maintainers:
    - volpatto
