{% set name = "spotpy" %}
{% set version = "1.6.4" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8846d0939577d19365c292e2ecf628fb0d8eb95377a8fd1b068d46a20c48ea2f

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps -vv '

requirements:
  host:
    - pip >=25.2
    - python {{ python_min }}
    - setuptools >=64
    - setuptools_scm >=6.4
  run:
    - python >={{ python_min }}
    - matplotlib-base >=3.0
    - mpi4py
    - numpy >=2.0
    - pandas >=1.0
    - scipy >=1.5.0

test:
  imports:
    - spotpy
    - spotpy.algorithms
    - spotpy.database
    - spotpy.examples
    - spotpy.examples.cmf_data
    - spotpy.examples.hymod_exe
    - spotpy.examples.hymod_python
    - spotpy.gui
    - spotpy.hydrology
    - spotpy.parallel
  requires:
    - python {{ python_min }}
    - click
    - docutils
    - numba
    - pathos
    - pip >=25.2
    - pytables
    - pytest
    - pytest-cov
  source_files:
    - pyproject.toml
    - tests 
  commands:
    - pip check
    - python -m pytest --cov spotpy --cov-report term-missing -v tests/

about:
  home: https://spotpy.readthedocs.io/en/latest/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Statistical Parameter Optimization Tool
  description: |
    SPOTPY is a Python framework that enables the use of Computational optimization techniques for calibration, 
    uncertainty and sensitivity analysis techniques of almost every (environmental-) model.
    The package is published in the open source journal PLoS One:

    Houska, T., Kraft, P., Chamorro-Chavez, A. and Breuer, L.: SPOTting Model Parameters Using a Ready-Made Python 
    Package, PLoS ONE, 10(12), e0145180, doi:10.1371/journal.pone.0145180, 2015.
  doc_url: https://spotpy.readthedocs.io/en/latest/
  dev_url: https://github.com/thouska/spotpy

extra:
  recipe-maintainers:
    - Zeitsperre
